### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#17]
Zoom the pic and see that the **Asr** and it's time is a little bit up than the **After** and it's time.
![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/dc5e5e48-1230-4edc-b93b-d58c8398874a)

**Comment by Khiro95** [comment]
Nice catch. My first guess is that there could be some rounding issue when the size of UI element is calculated. I will check and see.

**Comment by sfksuperman** [comment]
https://github.com/Khiro95/Awqat-Salaat/issues/13#issuecomment-2120457943

I am not sure whether it is caused by Network Monitor widget or this widget because when PC starts, all elements in the taskbar tries to load themselves and adjust and that's where it sometimes (not always but often) aligned in this way that they overlapped to each other. But they Re-Position button solves the problem anyhow!

**Comment by Khiro95** [comment]
@sfksuperman Unfortunately, that's the main issue with the widget because on Windows 11 there is no program to manage the position and alignment of the widgets inside the taskbar. So each widget has to take care of itself :(

And as far as I can tell, the **Traffic Monitor** widget changes its size dynamically to make its displayed data fits inside the widget.
With that being said, the only real solution for such cases is to give the widget a manual offset on the taskbar (https://github.com/Khiro95/Awqat-Salaat/issues/10#issuecomment-2083234935)

I really wish Microsoft brings back Deskband feature to Windows 11 or provide an equivalent alternative, the whole overlapping and positioning issues would disappear.

**Comment by Khiro95** [comment]
Fixed in v3.2.
