### ISSUE TITLE
Syuruq/Sunrise Time

### ISSUE THREAD

**Issue by Feyruzefendi** [Khiro95/Awqat-Salaat#20]
Salam Brother, just a sugestion, can you give option to add time for syuruq/sunrise? 
Jazakallah..

**Comment by Khiro95** [comment]
Salam @Feyruzefendi ,

Yes I can, and the services already provide this info but I'm not sure about its precision, that's why I didn't include it.
If it's important to you, I can add it in next version. If so, I will be grateful if you tell me how it's important, because I like to learn from the people how they are going to use the widget :)

**Comment by Feyruzefendi** [comment]
Thank you, it's important because we know, the time for Fajr prayer lasts from the onset of the true dawn until the sun starts to rise. So knowing when is the time limit for fajr prayer is a must. So i can adjust my alarm and my schedule. Especially in summer, where dawn starts at 3 and the sun already rises at 5. sometimes it's difficult to wake up on time, so knowing when the deadline is important.

**Comment by Khiro95** [comment]
> Thank you, it's important because we know, the time for Fajr prayer lasts from the onset of the true dawn until the sun starts to rise. So knowing when is the time limit for fajr prayer is a must. So i can adjust my alarm and my schedule. Especially in summer, where dawn starts at 3 and the sun already rises at 5. sometimes it's difficult to wake up on time, so knowing when the deadline is important.

Thank your for the clarification :)

**Comment by Khiro95** [comment]
@Feyruzefendi **Shuruq** time is now available in v3.2.
