### ISSUE TITLE
Remaining time is not showing

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#21]
I installed **AwqatSalaat.WinUI_Release-x64.msi** in my Windows 11 but it's not showing the remaining time of next prayer.

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/5b12940d-76b6-4385-9ff3-6c29958cb698)

But if I change the language to Arabic, it displays:

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/b8452a40-e3d7-4fd5-8cb7-aedbe92e4b84)

**Comment by Khiro95** [comment]
Hi @sfksuperman,

I think it's the issue of the space not being enough to show both the time and the countdown because one of these columns has larger width than expected, thus  the 2nd column disappear. That's exactly the same issue as #16. Although I've made tests to check that the space is enough, it seems that changing display scale has a side effect on size calculation precision.

However, I've made changes to that area in the next version (to support compact mode) and that issue should be gone for good since I have enlarged the width a little.

Thank you for raising this issue, I now have to make sure to check different display scales before releasing updates to avoid such issues again 😅

**Comment by Khiro95** [comment]
You may need to disable showing seconds for now if you need the widget in English.

**Comment by sfksuperman** [comment]
Thank you, @Khiro95. My work laptop is set to 125%, while my personal laptop is set to 150%. This clearly indicates that screen resolution has a direct impact.

**Comment by Khiro95** [comment]
@sfksuperman This issue is now fixed in v3.2
