### ISSUE TITLE
Position of the widget in Taskbar - Overlapped with another widget!

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#8]
Can we adjust the position of the widget across the taskbar (because it's overlapping with another widget which I have to show network speed)?

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/5e38c9a4-7adc-4c16-bb95-1301c96975b3)

**Comment by Khiro95** [comment]
@sfksuperman Unrelated question: Are you using a display scale other than 100%? Because in your screenshot the widget look *clipped*.

**Comment by sfksuperman** [comment]
As per my Windows setting, it is set to 125%. Also, check the latest image below (after fixing the location issue).

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/7c00ac5b-ddd5-4b62-87f0-7884e1f35e74)

**Comment by Khiro95** [comment]
Thank you very much

**Comment by Khiro95** [comment]
In the next version, overlapping issue is fixed at taskbar root level. I will see if I can continue with other levels as well.
![fix_overlapping](https://github.com/Khiro95/Awqat-Salaat/assets/126525910/4bb76cab-160d-45fd-a013-e497eebaf84e)

**Comment by sfksuperman** [comment]
If I suggest, keep the widget to show only the upcoming namaz time with a name like **Asr 03:10 PM** (_12h or 24h format, whatever a person has set in setting_) and keep a functionality that it will show all the times of **5 main prayers** with timing upon hovering over the widget for 1 sec.

Below is the screenshot for reference:

Upon hovering:
![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/7e3c3f4c-bbaa-4c60-9eaf-350790901f88)

**Comment by Khiro95** [comment]
> Keep the countdown timing in smaller font size and if possible, then add the seconds as well.

There are some considerations regarding widget's pane on the taskbar:
- It should not clutter the taskbar
- It should take the least possible space
- It should be consistent with the taskbar design as much as possible.

So here are some issues that I see in your suggestion:
- Using smaller font size, on any part, will have negative impact on readability. This may not be an issue for you since you have 125% display scale, but with 100% scale it will not look good.
- In your screenshot, the widget width looks fine when you used **Asr**, but that's the smallest name possible. Try with **Maghrib** and you will see a serious issue :)
- Using different font sizes and different font weights will break design consistency with taskbar design.

However, the suggestion for displaying the seconds in countdown is feasible.

Also I want to let you know that I'm already thinking to add **compact** mode where widget's width become smaller and then alternate the display of the next prayer time and countdown. It means that, for example, the widget shows prayer time for a second then display the countdown in the next second then repeat.

Thanks for the suggestion and let me know what you think.

**Comment by sfksuperman** [comment]
That's a great idea, but regarding the screen resolution, even my 14-inch small laptop has default 125% zoom, and on 17-inch laptops have the same 125% or 150% (rare, never seen).
But still, the wording should not break so yeah you can keep the font size workable in all screen resolutions (100% or 125%).

**Seconds** is crazy to have this feature, tick tok tick tok 😂

**Comment by Khiro95** [comment]
> That's a great idea, but regarding the screen resolution, even my 14-inch small laptop has default 125% zoom, and on 17-inch laptops have the same 125% or 150% (rare, never seen). But still, the wording should not break so yeah you can keep the font size workable in all screen resolutions (100% or 125%).

Your laptops most probably have high-resolution screens such as QHD or even 4K :) That's why Windows will look very small and need to increase the scale

> **Seconds** is crazy to have this feature, tick tok tick tok 😂

I used to show the seconds in the clock of my laptop in the past, it's very helpful :)

**Comment by Khiro95** [comment]
@sfksuperman v3.1 is released now, it should no longer overlap other widgets as long as there is enough space.
Also you can enable seconds in the countdown.

I will close this issue but feel free to re-open it if you find something not working.

**Comment by sfksuperman** [comment]
Wow!
![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/7c7c089a-dde3-4c55-87b8-16b3e859899e)
