### ISSUE TITLE
Can we have 12h clock as well instead of only 24h?

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#9]
👆

**Comment by Khiro95** [comment]
yes, Insha'Allah

**Comment by Khiro95** [comment]
@sfksuperman v3.1 is released now, the widget will now use the same time format of the system.

**Comment by sfksuperman** [comment]
@Khiro95 That's great bro! And now it's placed in the correct position. I have a few questions/suggestions if you don't mind:

1. If possible, put **h** for _hour_ in **After** time.
2. No 24h clock setting?
3. What **Re-Position** is for? Can we not place the widget anywhere on the taskbar (empty space without overlapping on other app icons) like a floating window?
4. Where is the **Setting** page for this app? I can't find it.
5. Please include a version in the app name, e.g., **AwqatSalaat.WinUI_Release-v3.1-x64**.

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/c889f90b-0a21-4102-811d-2fe546e96ebd)

**Comment by Khiro95** [comment]
Hi @sfksuperman,
1. Is it important to have **h** in the countdown? After **h**, we will need to add **m** and then **s**,  and that will make the widget unnecessarily look busy, no?
2. Time format follows settings configuration, so there is no manual setting at the moment. What you think?
3. The widget ***must*** be a floating window because Microsoft didn't give us a choice :( The **Re-position** command is used to update the widget's position, as best as possible, when it miss changes happened inside the taskbar that makes the current position undesirable.
4. Good idea :)

**Comment by sfksuperman** [comment]
@Khiro95 
1. No! leave it :)
2. Which setting? I can't see Time/Date Format in any setting, please navigate me.
3. Yeah got it!
4. Lol, yeah!

**Comment by Khiro95** [comment]
> 2. Which setting? I can't see Time/Date Format in any setting, please navigate me.

@sfksuperman Sorry, I forgot to type "system", so I mean time format follows **system** settings. That means when you change ***Short time*** format, the widget will pick-up this configuration and use it to display time.
![image](https://github.com/Khiro95/Awqat-Salaat/assets/126525910/a7260701-0127-4db9-8073-e1917609684b)
